# Generated by Django 5.2.1 on 2025-09-29 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_cartdetails_categorydetails_productdetails_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplierdetails",
            name="state",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
