# Generated by Django 5.2.1 on 2025-09-29 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_supplierdetails_state"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartdetails",
            name="product",
        ),
        migrations.RemoveField(
            model_name="cartdetails",
            name="user",
        ),
    ]
