# Generated by Django 5.2.1 on 2025-09-29 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_remove_cartdetails_product_remove_cartdetails_user"),
        ("user", "0003_cartdetails_alter_orderdetails_cart"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CartDetails",
        ),
    ]
